### PR TITLE
Updated 1857 fort tejon earthquake page

### PR DESCRIPTION
**Pull request by tkalin-usgs**

### CODE REVIEW

**Comment by lisa-usgs** [comment]
Looks good!  A few comments:
1) Put the table and image in a row with 2 columns, image on the right.
2) Drop the <hr/>
3) Change the <h4>'s to <h3>'s
4) remove the <small> tags
5) remove longdesc="Fort Tejon, Califronia" in image
6) remove extra <p></p>'s
7) Change "Additional links:" to "For More Information:"
8) remove "<p> There is not a great deal of information about the Great 1857 Fort Tejon earthquake, but these links provide some information that is available about this event:</p>"
9) Tag the list below "For More Information:" with <ul><li>, etc
10) For the format of each item in that list, it'll be easier for me to just tell you quickly
10) Change <p><strong>References</strong></p> to <h3>References</h3>
11) Indents are too large - indent 2 spaces each time

I think that's it.
Thanks!

**Comment by lisa-usgs** [comment]
Wow, github rendered the HTML in my comment even though I put in a <pre>.  Just come by and talk to me instead, since the comment is not readable.

**Comment by lisa-usgs** [comment]
The original comment is now readable, yay for backtics!

**Comment by tkalin-usgs** [comment]
I updated the page, I believe it pushed correctly. Let me know.

**Comment by tkalin-usgs** [comment]
I updated the page with the 7.9 changes.

**Pull request merged**
