### PR TITLE
Update scenario catalog pages to provide a link to the map/list

### PR DESCRIPTION
**Pull request by ehunter-usgs**
@lisa-usgs This is a general mock for the link to the map. I've included an image to show what it should look like with the placeholder text/image.

screen shot 2016-12-21 at 2 06 34 pm

### CODE REVIEW

**Comment by lisa-usgs** [comment]
Looks good Eddie!  I'll make my updates as soon as I can, although today is my last scheduled day to work until Jan 9.

**Comment by jmfee-usgs** [comment]
Can we use more descriptive catalog text?  e.g. `View the Alaska Legacy Catalog` or `Alaska Legacy Scenario Catalog Map`

**Comment by lisa-usgs** [comment]
Yes, we're going to do that.  I'll be updating the link text and adding an icon on each catalog page when I'm not on AL.

**Comment by lisa-usgs** [comment]
I'm going to merge this to development and then swap in the icons that I've prepared and merge and deploy to production.

**Pull request merged**
