### PR TITLE
Design maps

### PR DESCRIPTION
**Pull request by jdbrown-USGS**
Adds static pages and links to data that has been moved from ehpmaster to team ftp.

### CODE REVIEW

**Comment by lisa-usgs** [comment]
1) The left nav should be the nav for the Hazards section which I haven't created yet, but will be doing so this week.  The left nav you created here will be the nav at the next level below.

2) The Worldwide Design Tool should be removed from the left nav.

3) Should the current and beta links also be in the left nav?  Also, the "US Seismic..." in the nav should be "U.S. Seismic..."

4) Since there is no longer a Worldwide Design Tool, the subheader "Sites in the U.S. and its Territories" is no longer needed. Then the <h#> level of the 3 design tool links can be bumped up.

5) The link at the bottom of the page "Looking for seismic zones?" should match the title of the page, which is "Help Selecting a Seismic Design Tool".

6) The "Use the Application" button at the top of the U.S. Design Maps page is too tiny.  It needs to stand out more.

**Comment by jdbrown-USGS** [comment]
- Removed references to Worldwide design tool and relevant files.
- Updated text in navigation
- Changed link name "Looking for seismic zones?"
- Changed button styles
- Updated references styles on usdesigndoc.php

**Comment by lisa-usgs** [comment]
/designmaps/usdesigndoc.php reference list needs `<ul class='referencelist'>`

is the link "Mapped design values" on /designmaps/usdesign.php supposed to go to a static page?

**Comment by jdbrown-USGS** [comment]
- Added reference styles
- Added pdf static section with links to data located on team FTP

**Pull request merged**
